spring:
  cloud:
    gateway:
      default-filters:
      - TokenRelay
      routes:
      - id: api-service
        uri: http://localhost:9090
        predicates:
        - Path=/api/v1/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: keycloak
            client-id: gateway
            client-secret: 8db5b66c-3a81-4b35-b024-b4569be23d40
            redirect-uri: 'http://localhost:8080/login/oauth2/code/{registrationId}'
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/dev
            user-name-attribute: preferred_username
